{{- $root:= . }}
{{- with .Values.headless}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ required ".Values.headless.name must be specified" .name }}
  labels:
    app: {{ $root.Values.app }}
spec:
  podSelector:
    matchLabels:
      app: {{ required ".Values.app must be specified" $root.Values.app }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ required ".Values.app must be specified" $root.Values.app }}
{{- end }}
