{{- $root:= . }}
{{- range $key, $secret:= .Values.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" $root }}-{{ $key }}
  labels:
    app: {{ $root.Values.app }}

stringData:
  {{- range $key, $value:= $secret.values }}
  {{ $key }}: |-{{ $value | nindent 4}}
  {{- end }}
---
{{- end }}
