{{- $root:= . }}
{{- with .Values.ports }}
apiVersion: v1
kind: Service
metadata:
  {{- if $root.Values.service }}
  name: {{ required "service.name must be specified" $root.Values.service.name }}
  {{- else }}
  name: {{ template "fullname" $root }}
  {{- end }}
  labels:
    app: {{ $root.Values.app }}

spec:
  type: ClusterIP
  selector:
    deploymentConfig: {{ template "fullname" $root }}
  ports:
  {{- range $key, $port:= .}}
    - name: {{ $key }}
      port: {{ required "port.port must be specified" $port.port }}
      protocol: TCP
      targetPort: {{ default $port.port $port.target }}
  {{- end }}
---
{{- end }}
