{{/*
deployment:
  meta:
  strategy: # default is rolling
  minReadySeconds: # minimum ready seconds
  autoscaling:
    meta:
    minReplicas: 1
    maxReplicas: 100
    targetCPU: 80
    targetMemory: 80

*/}}
{{- with .Values.deployment }}
{{ include "k8s-rocker.object" (list $ "apps/v1" "Deployment" (include "k8s-rocker.name"  $  ) .)
}}
spec:
  selector:
    matchLabels:
    {{- include "k8s-rocker.matchLabels" (list $) | indent 6}}
  minReadySeconds: {{ default 0 .minReadySeconds }}
  strategy:
    type: {{ default "RollingUpdate" .strategy }}
  template:
    metadata:
      labels:
      {{- include "k8s-rocker.matchLabels" (list $) | indent 8 }}
    spec:
      restartPolicy: {{ default "Always" $.Values.deployment.restart}}
    {{- with $.Values.init }}
      initContainers:
      {{- range $name, $init := . }}
      - {{- include "k8s-rocker.container" (list $ $name $init) | indent 10 }}
      {{- end }}
    {{- end }}

      containers:
        {{- range $name, $container := $.Values.pod }}
        - {{- include "k8s-rocker.container" (list $ $name $container) | indent 10 }}
        {{- end }}

{{- end }}
