{{/*
secrets:
  'name':
    'key': |
      data
    'key2':
      file: test/secrests/test.yaml
*/}}
{{- with .Values.secrets }}
{{- range $name, $secret:= . }}
{{ include "k8s-rocker.object" (list $ "v1" "Secret" $name $secret)
}}
stringData:
  {{- range $key, $value:= $secret.strings}}
  {{ $key }}: |-{{ $value | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value:= $secret.binary}}
  {{ $key }}: |-{{ b64enc ($.Files.Get $value.file) | nindent 4 }}
  {{- end }}
---
{{- end }}{{/** end of range */}}
{{- end }}{{/** end of .Values.secrets */}}
