{{- $root := . }}
{{- range $key, $volume:= .Values.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" $root }}-{{ $key }}
  labels:
    app: {{ $root.Values.app }}
  {{- include "annotations" $volume.annotations | indent 2 }}

spec:
  accessModes:
    - {{ default "ReadWriteOnce" $volume.accessMode }}
  resources:
    requests:
      storage: {{ required ".Values.volume.storage must be defined" $volume.storage }}
---
{{- end }}
