{{- $root:= . }}
{{- with .Values.headless}}
apiVersion: v1
kind: Service
metadata:
  name: {{ required ".Values.headless.name must be specified" .name }}
  labels:
    app: {{ $root.Values.app }}
{{- with .ports}}
spec:
  clusterIP: None
  selector:
    deploymentConfig: {{ template "fullname" $root }}
  ports:
  {{- range $key, $port:= .}}
    - name: {{ $key }}
      port: {{ required "headless.port must be specified" $port.port }}
      protocol: TCP
      targetPort: {{ default $port.port $port.target }}
  {{- end }}
  {{- end }}
---
{{- end }}
