{{- $root := . }}
{{- range $key, $route:= .Values.routes}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "fullname" $root }}-{{ $key }}
  labels:
    app: {{ $root.Values.app }}
  {{- include "annotations" $route.annotations | indent 2 }}
spec:
  host: {{ required "route.host must be specified" $route.host }}
  {{- with $route.path }}
  path: {{ . }}
  {{- end }}
  port:
    targetPort: {{ required "route.port must be specified" $route.port }}
  tls:
    termination: {{ default "edge" $route.termination }}
  to:
    kind: Service
    {{- if $root.Values.service }}
    name: {{ $root.Values.service.name }}
    {{- else }}
    name: {{ template "fullname" $root}}
    {{- end }}

---
{{- end }}
