ingress:
  'name':
    meta:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        kubernetes.io/ingress.class: traefik
    class: traefik
    hosts:
      'host.of.app':
          '/':
            pathType: 'Prefix'
            to: 'servicename'
            port: 8080
