# features:
# make everything optional, allowing secrets only etc
#
# TODO:
# container.envFrom
# -> https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
nameOverride: # defaults to .Chart.Name

meta: # added to all objects
  labels:
    # app: is automatically added with the name of the install
    metalabel: foo
  annotations:
    metaannotation: bar

volumes:
  'myVolumeName':
    meta:
      annotations:
        bar: baz
        vol: 1
      labels:
        foo: bar
    mode: 'ReadWriteOnce'
    storage: '500Mi'

secrets:
  'name':
    meta:
      labels:
        foo: bar
      annotations:
        bar: baz
    strings:
      'key': |
         some sting value
         possibly multiline
    binary:
      'key2':
        file: test/secrets/file.secret
      'key3':
        file: test/secrets/image.jpg

configmaps:
  'name':
    meta:
      labels:
        foo: bar
      annotations:
        bar: baz
    data:
      'key': value
      'key2': value2

containers:
  'name':
    image: nginx
    tag: latest
    policy: 'IfNotPresent' # imagePullPolicy
    command: # startup command
      - echo
      - foo
    args: # startup args
      - bla
      - blub
    ports:
      'name':
        port: 80
        protocol: 'TCP'
    env:
      'name': 'SOME_ENV_VALUE'
      'raw-from':
        raw:
          somewhere: foo
    health: # healthchecks
      restart: 'Always' # restartPolicy
    mounts: # mounts
      volumes:
        'name':
          path:
      secrets:
      env: # TODO
      configmaps:
    affinity: # passed raw into the affinity block

test:
  # podspec as above, used for helm test

initContainers:
  # podspec

deployment:
  meta:
  strategy: 'RollingUpdate' # default is rolling
  minReadySeconds: 0 # minimum ready seconds
  autoscaling:
    meta:
    minReplicas: 1
    maxReplicas: 100
    targetCPU: 80
    targetMemory: 80

statefulset:
  meta:
  replicaCount: 1
  policy: 'OrderedReady'
  strategy: 'RollingUpdate'
  minReadySeconds: # minimum ready seconds

services:
  meta:
  'name':
    port: 80
    target: 80 # defaults to port
    meta: # additional metadata

ingress:
  'name':
    meta:
    hosts:
      'host.of.app':
          '/':
            pathType: 'Prefix'
            to: 'servicename'
            port: 8080
